import "../styles/globals.css";
import type { Metadata } from "next";
import AppNavbar from "../components/AppNavbar";
import Container from "@mui/material/Container";
import darkTheme from "../styles/theme/darkTheme";
import font from "../styles/theme/font";
import { ThemeProvider, CssBaseline, Box } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider theme={darkTheme}>
        <CssBaseline />
        <body className={font.className}>
          <Box style={{ position: "relative" }}>
            <Box style={boxStyles}></Box>
            <AppNavbar />
            <Container>{children}</Container>
          </Box>
        </body>
      </ThemeProvider>
    </html>
  );
}

const boxStyles = {
  top: 0,
  left: 0,
  position: "absolute",
  backgroundImage: "url('imgs/waves.png')",
  backgroundRepeat: "no-repeat",
  backgroundSize: "contain",
  backgroundPosition: "center center",
  width: "100%",
  height: "100%",
  zIndex: "-1",
  opacity: "0.2",
};
